/**
 * Smart Contract Interaction Layer
 *
 * Provides typed wrappers for all Nexus smart contracts on 0G Chain.
 * Uses ethers.js v6 for contract interaction.
 *
 * Contracts:
 * - NexusAgentINFT: Agent identity (ERC-7857)
 * - SkillRegistry: Skill marketplace
 * - ReputationEngine: On-chain reputation
 * - AgentEscrow: Trustless task escrow
 */

import { ethers } from "ethers";

const RPC_URL = process.env.OG_RPC_URL || "https://evmrpc.0g.ai";

// Contract addresses (set after deployment)
const CONTRACTS = {
  agentINFT: process.env.NEXUS_AGENT_CONTRACT || "",
  skillRegistry: process.env.SKILL_REGISTRY_CONTRACT || "",
  reputation: process.env.REPUTATION_CONTRACT || "",
  escrow: process.env.ESCROW_CONTRACT || "",
};

// Minimal ABIs for interaction (full ABIs generated by Hardhat)
const AGENT_ABI = [
  "function mintAgent(address to, string encryptedURI, bytes32 metadataHash) returns (uint256)",
  "function secureTransfer(address from, address to, uint256 tokenId, bytes sealedKey, bytes proof)",
  "function clone(address to, uint256 tokenId, bytes sealedKey, bytes proof) returns (uint256)",
  "function authorizeUsage(uint256 tokenId, address executor, bytes permissions)",
  "function revokeUsage(uint256 tokenId, address executor)",
  "function isAuthorized(uint256 tokenId, address executor) view returns (bool)",
  "function equipSkill(uint256 agentId, string skillId)",
  "function getAgent(uint256 tokenId) view returns (string, bytes32, uint256, uint256, string[])",
  "function ownerOf(uint256 tokenId) view returns (address)",
  "function totalSupply() view returns (uint256)",
  "event AgentMinted(uint256 indexed tokenId, address indexed owner, bytes32 metadataHash)",
];

const SKILL_ABI = [
  "function createSkill(string name, string description, string encryptedURI, bytes32 metadataHash, uint256 pricePerUse, uint256 subscriptionPrice) returns (uint256)",
  "function payForUse(uint256 skillId) payable",
  "function subscribe(uint256 skillId) payable",
  "function getSkill(uint256 skillId) view returns (tuple(string name, string description, string encryptedURI, bytes32 metadataHash, address creator, uint256 pricePerUse, uint256 subscriptionPrice, uint256 totalUses, uint256 totalRevenue, uint256 createdAt, bool active))",
  "function isAuthorizedUser(uint256 skillId, address user) view returns (bool)",
  "event SkillCreated(uint256 indexed skillId, address indexed creator, string name)",
];

const REPUTATION_ABI = [
  "function recordAction(uint256 agentId, uint8 dimension, uint256 score, bytes32 daProofHash)",
  "function getReputation(uint256 agentId) view returns (tuple(uint256 accuracy, uint256 reliability, uint256 safety, uint256 collaboration, uint256 totalActions, uint256 lastUpdated))",
  "function getCompositeScore(uint256 agentId) view returns (uint256)",
  "event ReputationUpdated(uint256 indexed agentId, uint8 dimension, uint256 newScore)",
];

const ESCROW_ABI = [
  "function createTask(uint256 agentId, address agentOwner, string description) payable returns (uint256)",
  "function startTask(uint256 taskId)",
  "function completeTask(uint256 taskId, bytes32 resultHash, bytes32 daProofHash)",
  "function releasePayment(uint256 taskId)",
  "function disputeTask(uint256 taskId)",
  "function getTask(uint256 taskId) view returns (tuple(uint256 id, address requester, uint256 agentId, address agentOwner, uint256 payment, string description, bytes32 resultHash, bytes32 daProofHash, uint8 status, uint256 createdAt, uint256 completedAt, uint256 disputeDeadline))",
  "event TaskCreated(uint256 indexed taskId, address indexed requester, uint256 indexed agentId, uint256 payment)",
];

function getProvider() {
  return new ethers.JsonRpcProvider(RPC_URL);
}

function getSigner() {
  const provider = getProvider();
  return new ethers.Wallet(process.env.PRIVATE_KEY!, provider);
}

export function getAgentContract(signerOrProvider?: ethers.Signer | ethers.Provider) {
  return new ethers.Contract(CONTRACTS.agentINFT, AGENT_ABI, signerOrProvider || getSigner());
}

export function getSkillContract(signerOrProvider?: ethers.Signer | ethers.Provider) {
  return new ethers.Contract(CONTRACTS.skillRegistry, SKILL_ABI, signerOrProvider || getSigner());
}

export function getReputationContract(signerOrProvider?: ethers.Signer | ethers.Provider) {
  return new ethers.Contract(CONTRACTS.reputation, REPUTATION_ABI, signerOrProvider || getSigner());
}

export function getEscrowContract(signerOrProvider?: ethers.Signer | ethers.Provider) {
  return new ethers.Contract(CONTRACTS.escrow, ESCROW_ABI, signerOrProvider || getSigner());
}

// ─── High-level helpers ──────────────────────────────────

export async function mintAgent(to: string, encryptedURI: string, metadataHash: string) {
  const contract = getAgentContract();
  const tx = await contract.mintAgent(to, encryptedURI, metadataHash);
  const receipt = await tx.wait();
  const event = receipt.logs.find((l: any) => l.fragment?.name === "AgentMinted");
  return { tokenId: event?.args?.[0], txHash: receipt.hash };
}

export async function createSkill(
  name: string,
  description: string,
  encryptedURI: string,
  metadataHash: string,
  pricePerUse: bigint,
  subscriptionPrice: bigint
) {
  const contract = getSkillContract();
  const tx = await contract.createSkill(name, description, encryptedURI, metadataHash, pricePerUse, subscriptionPrice);
  const receipt = await tx.wait();
  return { txHash: receipt.hash };
}

export async function recordReputation(
  agentId: number,
  dimension: number,
  score: number,
  daProofHash: string
) {
  const contract = getReputationContract();
  const tx = await contract.recordAction(agentId, dimension, score, daProofHash);
  return tx.wait();
}
