/**
 * Smart Contract Interaction Layer
 *
 * Provides typed wrappers for all Nexus smart contracts on 0G Chain.
 * Uses ethers.js v6 for contract interaction.
 *
 * Contracts:
 * - NexusAgentINFT: Agent identity (ERC-7857)
 * - SkillRegistry: Skill marketplace
 * - ReputationEngine: On-chain reputation
 * - AgentEscrow: Trustless task escrow
 */

import { ethers } from "ethers";

function getRpcUrl() {
  return process.env.OG_RPC_URL || "https://evmrpc.0g.ai";
}

// Contract addresses — lazy read to ensure dotenv is loaded first
function getContracts() {
  return {
    agentINFT: process.env.NEXUS_AGENT_CONTRACT || "",
    skillRegistry: process.env.SKILL_REGISTRY_CONTRACT || "",
    reputation: process.env.REPUTATION_CONTRACT || "",
    escrow: process.env.ESCROW_CONTRACT || "",
  };
}

// Minimal ABIs for interaction (full ABIs generated by Hardhat)
const AGENT_ABI = [
  "function mintAgent(address to, string encryptedURI, bytes32 metadataHash) returns (uint256)",
  "function secureTransfer(address from, address to, uint256 tokenId, bytes sealedKey, bytes proof)",
  "function clone(address to, uint256 tokenId, bytes sealedKey, bytes proof) returns (uint256)",
  "function authorizeUsage(uint256 tokenId, address executor, bytes permissions)",
  "function revokeUsage(uint256 tokenId, address executor)",
  "function isAuthorized(uint256 tokenId, address executor) view returns (bool)",
  "function equipSkill(uint256 agentId, string skillId)",
  "function getAgent(uint256 tokenId) view returns (string, bytes32, uint256, uint256, string[])",
  "function ownerOf(uint256 tokenId) view returns (address)",
  "function totalSupply() view returns (uint256)",
  "function tokenByIndex(uint256 index) view returns (uint256)",
  "event AgentMinted(uint256 indexed tokenId, address indexed owner, bytes32 metadataHash)",
];

const SKILL_ABI = [
  "function createSkill(string name, string description, string encryptedURI, bytes32 metadataHash, uint256 pricePerUse, uint256 subscriptionPrice) returns (uint256)",
  "function payForUse(uint256 skillId) payable",
  "function subscribe(uint256 skillId) payable",
  "function getSkill(uint256 skillId) view returns (tuple(string name, string description, string encryptedURI, bytes32 metadataHash, address creator, uint256 pricePerUse, uint256 subscriptionPrice, uint256 totalUses, uint256 totalRevenue, uint256 createdAt, bool active))",
  "function isAuthorizedUser(uint256 skillId, address user) view returns (bool)",
  "function totalSupply() view returns (uint256)",
  "function tokenByIndex(uint256 index) view returns (uint256)",
  "function getActiveSkillCount() view returns (uint256)",
  "event SkillCreated(uint256 indexed skillId, address indexed creator, string name)",
];

const REPUTATION_ABI = [
  "function recordAction(uint256 agentId, uint8 dimension, uint256 score, bytes32 daProofHash)",
  "function getReputation(uint256 agentId) view returns (tuple(uint256 accuracy, uint256 reliability, uint256 safety, uint256 collaboration, uint256 totalActions, uint256 lastUpdated))",
  "function getCompositeScore(uint256 agentId) view returns (uint256)",
  "function getActionCount(uint256 agentId) view returns (uint256)",
  "function getActionProof(uint256 agentId, uint256 index) view returns (tuple(uint256 agentId, uint8 dimension, uint256 score, bytes32 daProofHash, uint256 timestamp))",
  "event ReputationUpdated(uint256 indexed agentId, uint8 dimension, uint256 newScore)",
];

const ESCROW_ABI = [
  "function createTask(uint256 agentId, address agentOwner, string description) payable returns (uint256)",
  "function startTask(uint256 taskId)",
  "function completeTask(uint256 taskId, bytes32 resultHash, bytes32 daProofHash)",
  "function releasePayment(uint256 taskId)",
  "function disputeTask(uint256 taskId)",
  "function getTask(uint256 taskId) view returns (tuple(uint256 id, address requester, uint256 agentId, address agentOwner, uint256 payment, string description, bytes32 resultHash, bytes32 daProofHash, uint8 status, uint256 createdAt, uint256 completedAt, uint256 disputeDeadline))",
  "function getNextTaskId() view returns (uint256)",
  "function getUserTasks(address user) view returns (uint256[])",
  "function getAgentTasks(uint256 agentId) view returns (uint256[])",
  "event TaskCreated(uint256 indexed taskId, address indexed requester, uint256 indexed agentId, uint256 payment)",
];

function getProvider() {
  return new ethers.JsonRpcProvider(getRpcUrl());
}

function getSigner() {
  const provider = getProvider();
  return new ethers.Wallet(process.env.PRIVATE_KEY!, provider);
}

export function getAgentContract(signerOrProvider?: ethers.Signer | ethers.Provider) {
  return new ethers.Contract(getContracts().agentINFT, AGENT_ABI, signerOrProvider || getSigner());
}

export function getSkillContract(signerOrProvider?: ethers.Signer | ethers.Provider) {
  return new ethers.Contract(getContracts().skillRegistry, SKILL_ABI, signerOrProvider || getSigner());
}

export function getReputationContract(signerOrProvider?: ethers.Signer | ethers.Provider) {
  return new ethers.Contract(getContracts().reputation, REPUTATION_ABI, signerOrProvider || getSigner());
}

export function getEscrowContract(signerOrProvider?: ethers.Signer | ethers.Provider) {
  return new ethers.Contract(getContracts().escrow, ESCROW_ABI, signerOrProvider || getSigner());
}

// ─── High-level helpers ──────────────────────────────────

export async function mintAgent(to: string, encryptedURI: string, metadataHash: string) {
  const contract = getAgentContract();
  const tx = await contract.mintAgent(to, encryptedURI, metadataHash);
  const receipt = await tx.wait();
  const event = receipt.logs.find((l: any) => l.fragment?.name === "AgentMinted");
  return { tokenId: event?.args?.[0], txHash: receipt.hash };
}

export async function createSkill(
  name: string,
  description: string,
  encryptedURI: string,
  metadataHash: string,
  pricePerUse: bigint,
  subscriptionPrice: bigint
) {
  const contract = getSkillContract();
  const tx = await contract.createSkill(name, description, encryptedURI, metadataHash, pricePerUse, subscriptionPrice);
  const receipt = await tx.wait();
  return { txHash: receipt.hash };
}

export async function recordReputation(
  agentId: number,
  dimension: number,
  score: number,
  daProofHash: string
) {
  const contract = getReputationContract();
  const tx = await contract.recordAction(agentId, dimension, score, daProofHash);
  return tx.wait();
}

// ─── On-chain list helpers ───────────────────────────────

/** List all agents from on-chain (ERC721Enumerable) */
export async function listAgents(): Promise<Array<{
  id: number;
  owner: string;
  encryptedURI: string;
  metadataHash: string;
  createdAt: string;
  clonedFrom: string;
  skills: string[];
}>> {
  const provider = getProvider();
  const contract = getAgentContract(provider);
  const total = Number(await contract.totalSupply());
  const agents = [];

  for (let i = 0; i < total; i++) {
    const tokenId = Number(await contract.tokenByIndex(i));
    const owner = await contract.ownerOf(tokenId);
    const agent = await contract.getAgent(tokenId);
    agents.push({
      id: tokenId,
      owner,
      encryptedURI: agent[0],
      metadataHash: agent[1],
      createdAt: agent[2].toString(),
      clonedFrom: agent[3].toString(),
      skills: agent[4],
    });
  }
  return agents;
}

/** List all skills from on-chain (ERC721Enumerable) */
export async function listSkills(): Promise<Array<{
  id: number;
  name: string;
  description: string;
  creator: string;
  pricePerUse: string;
  subscriptionPrice: string;
  totalUses: string;
  totalRevenue: string;
  active: boolean;
}>> {
  const provider = getProvider();
  const contract = getSkillContract(provider);
  const total = Number(await contract.totalSupply());
  const skills = [];

  for (let i = 0; i < total; i++) {
    const skillId = Number(await contract.tokenByIndex(i));
    const skill = await contract.getSkill(skillId);
    skills.push({
      id: skillId,
      name: skill.name,
      description: skill.description,
      creator: skill.creator,
      pricePerUse: skill.pricePerUse.toString(),
      subscriptionPrice: skill.subscriptionPrice.toString(),
      totalUses: skill.totalUses.toString(),
      totalRevenue: skill.totalRevenue.toString(),
      active: skill.active,
    });
  }
  return skills;
}

/** Build leaderboard from on-chain reputation data */
export async function getLeaderboard(): Promise<Array<{
  agentId: number;
  owner: string;
  accuracy: string;
  reliability: string;
  safety: string;
  collaboration: string;
  totalActions: string;
  compositeScore: string;
}>> {
  const provider = getProvider();
  const agentContract = getAgentContract(provider);
  const repContract = getReputationContract(provider);
  const total = Number(await agentContract.totalSupply());
  const entries = [];

  for (let i = 0; i < total; i++) {
    const tokenId = Number(await agentContract.tokenByIndex(i));
    const owner = await agentContract.ownerOf(tokenId);
    const rep = await repContract.getReputation(tokenId);
    const composite = await repContract.getCompositeScore(tokenId);

    entries.push({
      agentId: tokenId,
      owner,
      accuracy: rep[0].toString(),
      reliability: rep[1].toString(),
      safety: rep[2].toString(),
      collaboration: rep[3].toString(),
      totalActions: rep[4].toString(),
      compositeScore: composite.toString(),
    });
  }

  // Sort by composite score descending
  entries.sort((a, b) => Number(b.compositeScore) - Number(a.compositeScore));
  return entries;
}

/** Get platform stats from on-chain */
export async function getPlatformStats(): Promise<{
  totalAgents: string;
  totalSkills: string;
  activeSkills: string;
}> {
  const provider = getProvider();
  const agentContract = getAgentContract(provider);
  const skillContract = getSkillContract(provider);

  const totalAgents = await agentContract.totalSupply();
  const totalSkills = await skillContract.totalSupply();
  const activeSkills = await skillContract.getActiveSkillCount();

  return {
    totalAgents: totalAgents.toString(),
    totalSkills: totalSkills.toString(),
    activeSkills: activeSkills.toString(),
  };
}

/** List all tasks from on-chain */
export async function listTasks(): Promise<Array<{
  id: number;
  requester: string;
  agentId: number;
  agentOwner: string;
  payment: string;
  description: string;
  status: number;
  createdAt: string;
}>> {
  const provider = getProvider();
  const contract = getEscrowContract(provider);
  const nextId = Number(await contract.getNextTaskId());
  const tasks = [];

  for (let i = 1; i < nextId; i++) {
    try {
      const task = await contract.getTask(i);
      tasks.push({
        id: Number(task.id),
        requester: task.requester,
        agentId: Number(task.agentId),
        agentOwner: task.agentOwner,
        payment: task.payment.toString(),
        description: task.description,
        status: Number(task.status),
        createdAt: task.createdAt.toString(),
      });
    } catch {
      // Skip invalid tasks
    }
  }
  return tasks;
}

/** Get action history for an agent from on-chain */
export async function getActionHistory(agentId: number): Promise<Array<{
  dimension: number;
  score: number;
  daProofHash: string;
  timestamp: string;
}>> {
  const provider = getProvider();
  const contract = getReputationContract(provider);
  const count = Number(await contract.getActionCount(agentId));
  const actions = [];

  for (let i = 0; i < count; i++) {
    const proof = await contract.getActionProof(agentId, i);
    actions.push({
      dimension: Number(proof.dimension),
      score: Number(proof.score),
      daProofHash: proof.daProofHash,
      timestamp: proof.timestamp.toString(),
    });
  }
  return actions;
}
